language: java

jdk:
 - oraclejdk8

#addons:
#  sonarqube:
#    token:
#      secure: 
#    branches:
#     - master
script:
   # other script steps might be done before running the actual SonarQube analysis
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -X sonar:sonar -Dsonar.host.url=https://sonarqube.com  -Dsonar.organization=yfengchan-github -Dsonar.login=$SONAR_QUBE_TOKEN
   #- mvn clean package
notifications:
   email: false
   
deploy:
   edge: true
   provider: cloudfoundry
   username: youfchen@126.com
   password: $PCF_TOKEN
   api: https://api.run.pivotal.io
   organization: youfchen-org
   space: development